---
- name: Disable root account
  become: true
  ansible.builtin.user:
    name: root
    password: '!'

- name: Installation des paquets communs
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - vim
    - locate
    
- name: Upgrade all package
  become: true
  apt:
    upgrade: dist
