---
- name: Installation des paquets communs
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - python3-pip
    - python3-venv
    - libssl-dev
    - libffi-dev
  delegate_to: localhost

- name: Install PyVmomi Python SDK for the VMware vSphere API
  ansible.builtin.pip:
    name: pyvmomi
    state: present
  become: true
  delegate_to: localhost
