---
- name: Installation des paquets communs
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - python3
    - python3-pip
    - pyvmomi
    - requests
