---
- name: Installation des paquets communs
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - python3-pip
    - python3-venv
    - libssl-dev
    - libffi-dev

- name: Installation de Pyvmomi pour vsphere ansible.builtin.apt
  pip:
    name: pyvmovi
    state: present
  become: true


