---
- name: Add Docker’s official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker APT repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
    state: present

- name: Install Docker
  ansible.builtin.apt:
    name: docker-ce
    state: present
    update_cache: true

- name: Ajouter le dépôt Kubernetes à sources.list.d
  ansible.builtin.shell: echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /" | tee /etc/apt/sources.list.d/kubernetes.list


- name: Télécharger et installer la clé GPG pour le dépôt Kubernetes
  ansible.builtin.shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      
- name: Mettre à jour la liste des paquets
  ansible.builtin.apt:
    update_cache: yes

# - name: update apt cache
#   ansible.builtin.apt:
#     update_cache: yes
#   register: update_result
      
- name: Install kubeadm, kubelet and kubectl
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - kubelet
    - kubeadm
    - kubectl

- name: Disable swap
  ansible.builtin.command: swapoff -a
  when: ansible_virtualization_type != "docker"

- name: Ensure swap is disabled on boot
  ansible.posix.mount:
    name: none
    fstype: swap
    state: absent

- name: Enable and start Docker
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
